/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-tint": "#a23c36",
        "on-error": "#ffffff",
        "inverse-primary": "#ffb4ac",
        "secondary": "#5f5e5e",
        "secondary-container": "#e2dfde",
        "surface": "#fbf9f8",
        "surface-bright": "#fbf9f8",
        "on-tertiary-container": "#999796",
        "on-secondary-fixed": "#1c1b1b",
        "on-secondary-fixed-variant": "#474746",
        "tertiary": "#1b1b1a",
        "surface-variant": "#e4e2e2",
        "outline-variant": "#ddc0bd",
        "primary-container": "#630d0d",
        "on-surface-variant": "#564240",
        "on-surface": "#1b1c1c",
        "secondary-fixed": "#e5e2e1",
        "inverse-surface": "#303031",
        "primary": "#410002",
        "tertiary-container": "#30302f",
        "on-tertiary": "#ffffff",
        "on-primary-fixed": "#410002",
        "surface-container-high": "#e9e8e7",
        "error-container": "#ffdad6",
        "surface-container-lowest": "#ffffff",
        "surface-dim": "#dbdad9",
        "on-secondary": "#ffffff",
        "surface-container-low": "#f5f3f3",
        "secondary-fixed-dim": "#c8c6c5",
        "on-secondary-container": "#636262",
        "primary-fixed": "#ffdad6",
        "on-error-container": "#93000a",
        "tertiary-fixed-dim": "#c8c6c4",
        "primary-fixed-dim": "#ffb4ac",
        "inverse-on-surface": "#f2f0f0",
        "tertiary-fixed": "#e5e2e0",
        "surface-container": "#efeded",
        "on-tertiary-fixed-variant": "#474745",
        "surface-container-highest": "#e4e2e2",
        "on-primary-fixed-variant": "#832521",
        "on-primary": "#ffffff",
        "on-primary-container": "#ec746a",
        "error": "#ba1a1a",
        "on-background": "#1b1c1c",
        "outline": "#8a716f",
        "on-tertiary-fixed": "#1b1c1b",
        "background": "#fbf9f8",
        "heritage-maroon": "#630d0d",
        "zen-white": "#FFFFFF",
        "ink-black": "#121212",
        "paper-grey": "#F2F2F2"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "lg": "24px",
        "container-max": "1280px",
        "xs": "4px",
        "sm": "8px",
        "gutter": "24px",
        "md": "16px",
        "xxl": "64px",
        "margin-mobile": "16px",
        "margin-desktop": "32px",
        "xl": "40px",
        "unit": "4px",
        "section-gap": "120px",
        "stack-sm": "8px",
        "stack-md": "16px",
        "stack-lg": "32px"
      },
      fontFamily: {
        "display": ["var(--font-eb-garamond)", "serif"],
        "headline": ["var(--font-eb-garamond)", "serif"],
        "body": ["var(--font-inter)", "sans-serif"],
        "label": ["var(--font-inter)", "sans-serif"]
      }
    },
  },
  plugins: [],
}
